### ISSUE TITLE
Crashes on config with lua options

### ISSUE THREAD

**Issue by budnix** [yandex/gixy#48]
I have custom nginx build with enabled support for lua (lua-nginx-module-0.10.0). I have declared a dynamic variable using `set_by_lua_file $myvar` and this can be an issue.

Part of my config
```
...
    set_by_lua_file $latest_ver conf/var_factory.lua;
...
```

Here's the stack trace
```
[context]	INFO	Can't find variable '1'
[context]	INFO	Can't find variable 'latest_hot'
[context]	INFO	Can't find variable 'latest_hot'
[context]	INFO	Can't find variable 'latest_hot'
Traceback (most recent call last):
  File "/usr/local/bin/gixy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gixy/cli/main.py", line 158, in main
    yoda.audit(path, fdata, is_stdin=False)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 31, in audit
    self._audit_recursive(self.root.children)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 46, in _audit_recursive
    self._audit_recursive(directive.children)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 46, in _audit_recursive
    self._audit_recursive(directive.children)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 46, in _audit_recursive
    self._audit_recursive(directive.children)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 41, in _audit_recursive
    self._update_variables(directive)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 56, in _update_variables
    for var in directive.variables:
  File "/usr/local/lib/python2.7/dist-packages/gixy/directives/directive.py", line 118, in variables
    for name, group in regexp.groups.items():
  File "/usr/local/lib/python2.7/dist-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/regexp.py", line 1004, in groups
    for name, parsed in extract_groups(self.parsed).items():
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/regexp.py", line 1025, in parsed
    self._parsed = sre_parse.parse(FIX_NAMED_GROUPS_RE.sub('(?P<\\1>', self.source))
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 707, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 311, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 666, in _parse
    p = _parse_sub(source, state)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 311, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 644, in _parse
    raise error("bad character in group name")
gixy.core.sre_parse.sre_constants.error: bad c
```

Gixy v0.1.4

**Comment by buglloc** [comment]
As I can see problem not with `set_by_lua_file` directive. Gixy failed to parse one of your regular expression :(
Gixy 0.1.5 have better error message for this case, can your run gixy again? It must to show the problematic regex.

Thanks :)

**Comment by budnix** [comment]
Ok, Thanks! I have tested with 0.1.5 and got:

```
Traceback (most recent call last):
  File "/usr/local/bin/gixy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gixy/cli/main.py", line 158, in main
    yoda.audit(path, fdata, is_stdin=False)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 31, in audit
    self._audit_recursive(self.root.children)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 46, in _audit_recursive
    self._audit_recursive(directive.children)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 46, in _audit_recursive
    self._audit_recursive(directive.children)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 46, in _audit_recursive
    self._audit_recursive(directive.children)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 41, in _audit_recursive
    self._update_variables(directive)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/manager.py", line 56, in _update_variables
    for var in directive.variables:
  File "/usr/local/lib/python2.7/dist-packages/gixy/directives/directive.py", line 118, in variables
    for name, group in regexp.groups.items():
  File "/usr/local/lib/python2.7/dist-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/regexp.py", line 1004, in groups
    for name, parsed in extract_groups(self.parsed).items():
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/regexp.py", line 1025, in parsed
    self._parsed = sre_parse.parse(FIX_NAMED_GROUPS_RE.sub('(?P<\\1>', self.source))
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 707, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 311, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 666, in _parse
    p = _parse_sub(source, state)
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 311, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/lib/python2.7/dist-packages/gixy/core/sre_parse/sre_parse.py", line 644, in _parse
    raise error("bad character in group name")
```

After some debugging (comment suspecious lines and test config again) I have found that this line occurs an error:
```
rewrite "^\/((?(?=(0\.(?:1[0-9]{1}|20)\.[0-1]{1}(?:\-beta\d+)?))(hole)|(.*)))/old-page.html(.*)?$" /$1/new-page.html permanent;
```

**Comment by dvershinin** [comment]
@budnix I've resolved this in my actively maintained fork [dvershinin/gixy](https://github.com/dvershinin/gixy) (available on PyPI as `gixy-ng`).

The fork has migrated from pyparsing to [crossplane](https://github.com/nginxinc/crossplane) for nginx config parsing. Lua blocks (`content_by_lua_block`, `set_by_lua_file`, etc.) are now properly handled.

Install with: `pip install gixy-ng`
